// <auto-generated />
namespace MekDB.Migration.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addordersantal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addordersantal));
        
        string IMigrationMetadata.Id
        {
            get { return "201707160437372_addordersantal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
