// <auto-generated />
namespace MekDB.Migration.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NullFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201712011138434_NullFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
