// <auto-generated />
namespace MekDB.Migration.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addImageToTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addImageToTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711280906010_addImageToTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
